console.log("----before swap----");
var sweety = "Sweety";
var cutie = "Cutie";
console.log("sweety: ", sweety, " cutie: ", cutie);
console.log("------after swap-----");
var temp = sweety;
sweety = cutie;
cutie = temp;
console.log("sweety:", sweety, " cutie:", cutie);
console.log("------------------------------");

console.log("------before swap--------");
var num1 = 100;
var num2 = 200;
var num3 =300;
console.log( "num1: ", num1, " num2: ", num2,"num3:",num3);
console.log('--------after swap---------');
var temp = num1;
num1 = num2;
num2=num3;
num3=temp;
console.log("num1:", num1, " num2:", num2,"num3:", num3);